### ISSUE TITLE
Transformer version

### ISSUE THREAD

**Issue by Kittyuzu1207** [pujari-rajkumar/compositional_learner#1]
Hi Pujari,

Thanks for your excellent work! I met a problem when reproducing. When running document_bert_embedding_computation.py, there comes an error . I found the ids_or_pair_ids is a list of words and I don't know what the problem is(maybe the transformer version? Mine is 4.10.0). Do you have any suggestions ?

`Traceback (most recent call last):
  File "data_processing/document_bert_embedding_computation.py", line 185, in <module>
    dembs = get_bert_embs(sorted_tps, is_parses=True, batch_size=100, max_sent_len=150)
  File "data_processing/document_bert_embedding_computation.py", line 134, in get_bert_embs
    batch_tensor = create_bert_emb(batch)
  File "data_processing/document_bert_embedding_computation.py", line 78, in create_bert_emb
    all_toks = tokenizer.batch_encode_plus(all_sents, pad_to_max_length=True, add_special_tokens=True, is_pretokenized=True)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2584, in batch_encode_plus
    **kwargs,
  File "/usr/local/miniconda3/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 543, in _batch_encode_plus
    ids, pair_ids = ids_or_pair_ids
ValueError: too many values to unpack (expected 2)`

**Comment by pujari-rajkumar** [comment]
Hi, sorry for the late reply. Let me check this and get back to you. I know that there is an issue after they updated the transformers version. I updated the code for my local repo. I need to check if I made those changes in the public repo.

**Comment by pujari-rajkumar** [comment]
I updated the code to account for the latest version of transformers. I am closing this issue now.
